### ISSUE TITLE
No code

### ISSUE THREAD

**Issue by grod** [froztcms/frozt#1]
I can't get it to run on my machine. I think maybe it's because there's no code in the repo.

Any ideas?

**Comment by magnus-eriksson** [comment]
First, install it using composer together with npm and gem (you need to add `--force` on all since it doesn't exist in neither of those repos).  

When it's done, create a new file called `index.html` in your document root with the content: `Froztcms` and save. 

Now you can browse to the page and you should see something.

**Comment by grod** [comment]
I'm running temple os and got it to work thanks to your suggestions. I also had to hack the mainframe and install a root kit on the motherboard and overclock the GPU. 
Thanks mate!
